### ISSUE TITLE
Booking-doctor-appointment project

### ISSUE THREAD

**Issue by M-AminAlizadeh** [M-AminAlizadeh/Booking-doctor-appointment-front-end#9]
Github links of the project:
1. [Front-end](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end)
2. [Back-end](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-back-end)

---

Our team consists of 4 people:

1. [Ngala](https://github.com/ngalamac)
2. [Redwan](https://github.com/ethred)
3. [Agustin](https://github.com/SaveryIV)
4. [Amin](https://github.com/M-AminAlizadeh)

---

Screenshot of Kanban board:

![Screenshot 2023-12-05 181120](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/67329484/05cec5b6-da5d-4975-b800-961f00e144b5)

Kanban board [Link](https://github.com/users/M-AminAlizadeh/projects/6)

**Comment by Meltrust** [comment]
Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that Does not contain a link to the kanban board

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by M-AminAlizadeh** [comment]
@Meltrust Thank you for the CR
But I don't see a part about adding a link to the Kanban board to the issue according to the requirements
![Screenshot 2023-12-05 190154](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/67329484/173e0a32-91d1-4b9a-8844-a995250bb653)

**Comment by Meltrust** [comment]
Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, for which the link is not public, and I cannot access it:

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/57421823/0db2af4a-c282-4c52-8e01-92116972ebd1)

Frontend projects section:

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/57421823/3f4a249e-edae-4597-b927-68c661133361)

Backend projects section:

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/57421823/36965c36-6f20-42a6-a0dc-37d923b20a89)

As an additional note, GitHub calls kanban boards "projects".

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/57421823/fdf0e4e9-e3f4-4914-8e92-94cf9468fedd)





Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by M-AminAlizadeh** [comment]
@Meltrust Thank you for the clear explanation

**Comment by Meltrust** [comment]
## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, assignees, and pointings according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
